[archive]
build_output_dir = 'Built'
archive_location = '\\us-aus-hilbuild\builds\niveristandadd-ons\custom devices\protection_addon'

[projects.cd]
path = 'Source\Protection and Counter Addon.lvproj'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpecAllTargets'
project = '{cd}'
build_spec = 'Engine Release'

[package]
type = 'nipkg'
name = 'protection-addon-{veristand_version}'
dev_xml_path = 'Source\Addon\Custom Device Protection and Counter Addon.xml'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}'

[[release.steps]]
name = 'Master Release'
type = 'githubRelease'
2019_release_branches = ["master",]